In [16]:
import pandas as pd
import numpy as np

In [25]:
#lire la base de données à partir du fichier csv phase2
ph2=pd.read_csv('Desktop\myL3\IA\TP_IA\Phase2.csv')
ph2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25192 entries, 0 to 25191
Data columns (total 42 columns):
duration                       25192 non-null int64
protocol_type                  25192 non-null object
service                        25192 non-null object
flag                           25192 non-null object
src_bytes                      25192 non-null int64
dst_bytes                      25192 non-null int64
land                           25192 non-null int64
wrong_fragment                 25192 non-null int64
urgent                         25192 non-null int64
hot                            25192 non-null int64
num_failed_logins              25192 non-null int64
logged_in                      25192 non-null int64
num_compromised                25192 non-null int64
root_shell                     25192 non-null int64
su_attempted                   25192 non-null int64
num_root                       25192 non-null int64
num_file_creations             25192 non-null int64
num_shells                     25192 non-null int64
num_access_files               25192 non-null int64
num_outbound_cmds              25192 non-null int64
is_host_login                  25192 non-null int64
is_guest_login                 25192 non-null int64
count                          25192 non-null int64
srv_count                      25192 non-null int64
serror_rate                    25192 non-null float64
srv_serror_rate                25192 non-null float64
rerror_rate                    25192 non-null float64
srv_rerror_rate                25192 non-null float64
same_srv_rate                  25192 non-null float64
diff_srv_rate                  25192 non-null float64
srv_diff_host_rate             25192 non-null float64
dst_host_count                 25192 non-null int64
dst_host_srv_count             25192 non-null int64
dst_host_same_srv_rate         25192 non-null float64
dst_host_diff_srv_rate         25192 non-null float64
dst_host_same_src_port_rate    25192 non-null float64
dst_host_srv_diff_host_rate    25192 non-null float64
dst_host_serror_rate           25192 non-null float64
dst_host_srv_serror_rate       25192 non-null float64
dst_host_rerror_rate           25192 non-null float64
dst_host_srv_rerror_rate       25192 non-null float64
class                          25192 non-null object
dtypes: float64(15), int64(23), object(4)
memory usage: 8.1+ MB

In [26]:
#afficher les 5 premières lignes
ph2.head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,class
0,0,tcp,ftp_data,SF,491,0,0,0,0,0,...,25,0.17,0.03,0.17,0.00,0.00,0.00,0.05,0.00,normal
1,0,udp,other,SF,146,0,0,0,0,0,...,1,0.00,0.60,0.88,0.00,0.00,0.00,0.00,0.00,normal
2,0,tcp,private,S0,0,0,0,0,0,0,...,26,0.10,0.05,0.00,0.00,1.00,1.00,0.00,0.00,anomaly
3,0,tcp,http,SF,232,8153,0,0,0,0,...,255,1.00,0.00,0.03,0.04,0.03,0.01,0.00,0.01,normal
4,0,tcp,http,SF,199,420,0,0,0,0,...,255,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,normal

In [27]:
#Combien de valeur null par colonne?
ph2.isnull().sum()

duration                       0
protocol_type                  0
service                        0
flag                           0
src_bytes                      0
dst_bytes                      0
land                           0
wrong_fragment                 0
urgent                         0
hot                            0
num_failed_logins              0
logged_in                      0
num_compromised                0
root_shell                     0
su_attempted                   0
num_root                       0
num_file_creations             0
num_shells                     0
num_access_files               0
num_outbound_cmds              0
is_host_login                  0
is_guest_login                 0
count                          0
srv_count                      0
serror_rate                    0
srv_serror_rate                0
rerror_rate                    0
srv_rerror_rate                0
same_srv_rate                  0
diff_srv_rate                  0
srv_diff_host_rate             0
dst_host_count                 0
dst_host_srv_count             0
dst_host_same_srv_rate         0
dst_host_diff_srv_rate         0
dst_host_same_src_port_rate    0
dst_host_srv_diff_host_rate    0
dst_host_serror_rate           0
dst_host_srv_serror_rate       0
dst_host_rerror_rate           0
dst_host_srv_rerror_rate       0
class                          0
dtype: int64

In [28]:
#appliquer un encodage one hoting coding sur les colonnes de type catégorique
ph2=pd.get_dummies(ph2) 
ph2.head()

,duration,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,num_failed_logins,logged_in,num_compromised,...,flag_RSTOS0,flag_RSTR,flag_S0,flag_S1,flag_S2,flag_S3,flag_SF,flag_SH,class_anomaly,class_normal
0,0,491,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
1,0,146,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
2,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0
3,0,232,8153,0,0,0,0,0,1,0,...,0,0,0,0,0,0,1,0,0,1
4,0,199,420,0,0,0,0,0,1,0,...,0,0,0,0,0,0,1,0,0,1

In [29]:
del  ph2['class_normal'] #supprimer la colonne class_normal# du dataframe

In [30]:
#Afficher les statistiques de la base en utilisant la fonction describe()
ph2.describe()

,duration,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,num_failed_logins,logged_in,num_compromised,...,flag_RSTO,flag_RSTOS0,flag_RSTR,flag_S0,flag_S1,flag_S2,flag_S3,flag_SF,flag_SH,class_anomaly
count,25192.000000,2.519200e+04,2.519200e+04,25192.000000,25192.000000,25192.00000,25192.000000,25192.000000,25192.000000,25192.000000,...,25192.000000,25192.000000,25192.000000,25192.000000,25192.000000,25192.000000,25192.000000,25192.000000,25192.000000,25192.000000
mean,305.054104,2.433063e+04,3.491847e+03,0.000079,0.023738,0.00004,0.198039,0.001191,0.394768,0.227850,...,0.012067,0.000834,0.019728,0.278223,0.003493,0.000834,0.000595,0.594355,0.001707,0.466140
std,2686.555640,2.410805e+06,8.883072e+04,0.008910,0.260221,0.00630,2.154202,0.045418,0.488811,10.417352,...,0.109189,0.028861,0.139068,0.448133,0.059001,0.028861,0.024395,0.491026,0.041280,0.498862
min,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,4.400000e+01,0.000000e+00,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
75%,0.000000,2.790000e+02,5.302500e+02,0.000000,0.000000,0.00000,0.000000,0.000000,1.000000,0.000000,...,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000
max,42862.000000,3.817091e+08,5.151385e+06,1.000000,3.000000,1.00000,77.000000,4.000000,1.000000,884.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [31]:
X = ph2.iloc[:,:-1] #Récupérer toutes les lignes et toutes les colonnes sauf la dernière colonne de la base
y = ph2['class_anomaly'] #Récupérer la colonne outcome qui représente le target et stocker la dans la vaiable y

In [32]:
#Diviser la base de donnée en deux sous-ensembles test et train avec une taille de 30%
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, stratify=y)

In [33]:
#Charger le grid search qui cherche les paramètres optimaux d'un modèle
from sklearn.model_selection import GridSearchCV
#Charger le classificateur KNN
from sklearn.neighbors import KNeighborsClassifier
grid_params={
    'n_neighbors':[3,5,7,9,11],
    'metric':['euclidean','manhattan']
}

#Créer un objet grid search avec les paramètres et le modèle à tester
gs=GridSearchCV(
    KNeighborsClassifier(),
    grid_params,
    cv=3 #nombre de folds dans la cross validation
)
gs_results=gs.fit(X_train, y_train) #lancer le grid search et la cross validation

In [34]:
gs_results.best_params_ #Afficher les meilleurs paramètres trouvés

{'metric': 'manhattan', 'n_neighbors': 3}

In [35]:
#Créer une instance knn avec les paramètres optimaux trouvés
knn= KNeighborsClassifier(n_neighbors=3,metric='manhattan')
#Lancer l'apprentissage
knn.fit(X_train, y_train)#entraîner le modèles
y_pred=knn.predict(X_test) #evaluer le modèles

In [36]:
#Afficher la matrice de confusion
from sklearn.metrics import  confusion_matrix
confusion_matrix(y_test, y_pred)

array([[4009,   26],
       [  29, 3494]], dtype=int64)

In [37]:
#afficher la précision et le rappel
from sklearn.metrics import precision_score, recall_score
print('precision=',precision_score(y_test,y_pred))
print('recall=',recall_score(y_test,y_pred))

precision= 0.9926136363636363
recall= 0.9917683792222538

In [38]:
#Appliquer une cross validation avec le knn ayant les paramètres optimaux
from sklearn.model_selection import cross_val_score
#create a new KNN model
knn_cv = KNeighborsClassifier(n_neighbors=3, metric='manhattan')#train model with cv of 5 
cv_scores = cross_val_score(knn_cv, X, y, cv=5)#print each cv score (accuracy) and average them
print(cv_scores)
print('F1={}'.format(np.mean(cv_scores)))

[0.99285573 0.99106966 0.99226037 0.99047241 0.98947786]
F1=0.9912272049270611

les changements apportés aux données c'est qu'il y a plus les classe qu'on en a pas besoin 
oui y a eu un impact sur les performances du classificateur et on a remarqué ça avec la nouvelle valeur du F1 score qui est pase de 0.92 a 0.99